version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: split_it

  express-api:
    image: "${secrets.DOCKERHUB_USERNAME}/express-api:latest"
    container_name: express-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:admin123@mongo:27017/split_it?authSource=admin"
      PORT: 3000
      HOST: "0.0.0.0"
      DB_NAME: "split_it"

volumes:
  mongo_data:
