# Node 23.3.0 image
FROM node:23.3.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000


# Environment variables
# local mongodb with docker admin:admin123
ENV MONGO_URI="mongodb://admin:admin123@mongo:27017/split_it"
ENV PORT=3000
ENV HOST="0.0.0.0"
ENV DB_NAME="split_it"


# Command to run the application
CMD ["node", "index.js"]