name: Deploy

on:
  workflow_run:
    workflows: ["Deploy to AWS EC2"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull 2005parth/express-api:latest
    - name: Delete Old docker container
      run: sudo docker rm -f express-api-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name express-api-container 2005parth/express-api:latest