name: Deploy

on:
  workflow_run:
    workflows: ["Deploy to AWS EC2"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: |
        echo "Pulling Docker image..."
        sudo docker pull 2005parth/express-api:latest

    - name: Deploy with Docker Compose
      run: |
        echo "Stopping and removing old containers..."
        sudo docker-compose down || true
        echo "Starting new containers with Docker Compose..."
        sudo docker-compose up -d
