name: Docker Image CI with Docker Hub push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t my-docker-image .

    # Push the Docker image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: docker push $DOCKERHUB_USERNAME/my-docker-image:latest