name: Deploy to AWS EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/express-api:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/express-api:latest

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/express-api:latest
          docker stop express-api || true
          docker rm express-api || true
          docker run -d --name express-api -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/express-api:latest